name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger from the GitHub UI
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history, including tags
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get Version from GitHub Tag or Commit SHA
      id: version
      run: |
        # Try to get the latest tag; if no tag, get the short commit SHA
        VERSION=$(git tag --sort=-creatordate | head -n 1)
        echo "VERSION=$VERSION"
        echo "::set-output name=VERSION::$VERSION"

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./src/Glosy
        platforms: linux/arm64
        push: true
        tags: |
          pawelptak/glosy:latest
        build-args: |
          VERSION=${{ env.VERSION }}